# Generated by Django 5.1.1 on 2024-12-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='MALE', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='hostel',
            field=models.CharField(default='YES', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
